### ISSUE TITLE
Multiple selects + free-text option creation

### ISSUE THREAD

**Issue by vict0rsch** [bluzky/nice-select2#21]
Hi!

thanks for this work, looks really promising. 
Do you have any plan to implement a feature similar to Select2's tags? https://select2.org/tagging#tagging-with-multi-value-select-boxes

Thanks!

**Comment by nirmalgoswami** [comment]
+1

**Comment by Tsjippy** [comment]
I have no plans nor time for this, but feel free to give it a go yourself!
