### ISSUE TITLE
extractData when page is reloaded

### ISSUE THREAD

**Issue by lhapaipai** [bluzky/nice-select2#25]
Hi !
Thanks for your nice select !
I can suggest you to use the javascript properties instead of html attributes in your extractData method.
If you refresh your page and you have selected some options in your select form. your options are not coded in the html attributes but are clearly visible to the user and accessible with javascript.

file : `src/js/nice-select2.js#L119`

```diff
    var attributes = {
-      selected: item.getAttribute("selected") != null,
+      selected: item.selected,
-      disabled: item.getAttribute("disabled") != null,
+      disabled: item.disabled,
       optgroup: item.tagName == 'OPTGROUP'
    };
```

**Comment by Tsjippy** [comment]
fixed
