### ISSUE TITLE
reset selection

### ISSUE THREAD

**Issue by bobolat** [bluzky/nice-select2#26]
how to reset selection or select the drop down use call function? already tried to call like usually we call value by id use jquery, the problem is it changed on native drop down only..not the new drop down means value is correct change but not in the ui. I still saw the prev selection.

**Comment by wahyuang** [comment]
Hi, did you solve the issue? 

I get the same issue while using form reset button. The value is reset, but the UI still showing prev selection.

**Comment by bobolat** [comment]
yes, you need to use update function to the param, something like this 
`voucher_select.update();`
