### ISSUE TITLE
Customize texts

### ISSUE THREAD

**Issue by garak** [bluzky/nice-select2#27]
It would be nice if one could customize texts like "Select an option", "Search...", "X selected"

**Comment by EduVillas** [comment]
For internationalization like 
`'Select an option...' => 'Selecione uma opçao...`

**Comment by calumk** [comment]
This is already possible with the `placeholder` option

eg:

``` 
{ searchable: true, placeholder : "Search... } 
```

**Comment by garak** [comment]
@calumk not really...
![Screenshot from 2022-04-18 19-01-11](https://user-images.githubusercontent.com/179866/163844095-3d4f83f9-e4ec-441b-87e7-04fff9e12276.png)

**Comment by calumk** [comment]
Ok, so not the "...Search", but the main text of the box for the placeholder can be changed.

I agree more customisation would be better

**Comment by kamilmaliszewski** [comment]
Exactly, for "multiple" there must be option to change word "Selected". I can't use it in multi-lang website now

**Comment by Tsjippy** [comment]
fixed, as of now
