### ISSUE TITLE
Any way to remove the dropdown animation / transition?

### ISSUE THREAD

**Issue by Christopher-Hayes** [bluzky/nice-select2#35]
I've tried removing the dropdown transition effect in CSS, which does remove the animation. But, it seems like due to the intermediate transition styles, the post-transition styles don't get applied for a noticeable delay. I couldn't find any docs for tweaking that.

The main problem I have is that the transition entrance animation feels sluggish. If possible I'd like it to show instantly. Not sure if there's some JS logic that is delaying the dropdown from showing.

**Comment by Christopher-Hayes** [comment]
So, digging into it a little more. The `open` class is getting added / removed immediately. But, there's ~500ms delay between the CSS class being added/removed and the dropdown visually changing.

**Comment by creativestate** [comment]
Hey Chris,

For me, removing the properties "-webkit-transition" and "transition" under the rule ".nice-select .nice-select-dropdown" in nice-select2.css provided an instantaneous dropdown with no delay or transition effect.

Hopefully that helps with your issue.

**Comment by Christopher-Hayes** [comment]
Thanks @creativestate, I think it was actually Chrome's element inspector that was causing the slowdown. Which is weird. Usually it doesn't cause much of a slowdown, but in this case I guess it did.
