### ISSUE TITLE
Add option to change search placeholder

### ISSUE THREAD

**Issue by LukeSavefrogs** [bluzky/nice-select2#37]
It would be very useful to add the possibility to **change the default text** for the input element used to **search** when `searchable` is set to `true`. 

As of now it shows only "Search...", which is not ideal when i need to customize the i18n of the app.
![image](https://user-images.githubusercontent.com/33452387/165402992-4f1b5429-3567-480f-86c7-13fc256c0658.png)

It could be something like this...
![image](https://user-images.githubusercontent.com/33452387/165402698-ffff67b5-856a-4a51-a764-d5535a5fc7f0.png)

I could provide a PR for this, since i think i'll either way fork this project and add the changes i need 😄

**Comment by Tsjippy** [comment]
fixed
