### ISSUE TITLE
HTML5 validation broken

### ISSUE THREAD

**Issue by inc-ali** [bluzky/nice-select2#40]
Unfortunately HTML5 validation is not working, if the initial select element has a required attribute, because it's hidden. The browser will fail with an error `An invalid form control with name='fieldname' is not focusable.`

Instead of hiding the element, we could apply a similar fix as described in https://github.com/Choices-js/Choices/issues/449.

**Comment by maradititsolutions** [comment]
I am having the same problem. You must add a property called Required. Please update the library.

**Comment by Tsjippy** [comment]
fixed as of now
