### ISSUE TITLE
Support for multiple as a boolean attribute

### ISSUE THREAD

**Issue by Baedda** [bluzky/nice-select2#44]
Since multiple attribute is a boolean attribute, it should be set like this: `<select multiple>`.
But nice-select only enables its multi functionality if I set it in this outdated manner `<select multiple="multiple">`.

**Comment by nirmalgoswami** [comment]
+1

**Comment by Tsjippy** [comment]
fixed

**Comment by Baedda** [comment]
@Tsjippy could you also please update the npm package with version 2.1.0?
https://www.npmjs.com/package/nice-select2
