### ISSUE TITLE
Possibility to translate/change the labels/texts

### ISSUE THREAD

**Issue by Baedda** [bluzky/nice-select2#45]
It would be great to have options to customize the texts the library sets. For example _Search..._ in the input or _3 selected_ if you select three items.

**Comment by Tsjippy** [comment]
fixed

**Comment by Baedda** [comment]
@Tsjippy nice to hear!
Can you also publish a new package so we can install v2.1.0 via npm?

**Comment by Tsjippy** [comment]
I think I did yesterday

**Comment by Baedda** [comment]
Ah allright!
Thanks @Tsjippy! 
Will check it out tomorrow.
