### ISSUE TITLE
customize the html of each option

### ISSUE THREAD

**Issue by pablomadariaga** [bluzky/nice-select2#50]
How can you customize the html of each option? I need to show an icon for each option
![image](https://user-images.githubusercontent.com/69119357/213541621-932a987a-139a-4854-b455-6c7dc001b28f.png)

**Comment by pablomadariaga** [comment]
What if you put a `data-icon=""` and that the value can be an html svg or img.

**Comment by Tsjippy** [comment]
you can use the data-display for that
