### ISSUE TITLE
src source is wrong

### ISSUE THREAD

**Issue by ggcatalin** [bluzky/nice-select2#53]
in [package.json](https://github.com/bluzky/nice-select2/blob/master/package.json)
there is 
"main": "src/js/nice-select.js",
and should be "src/js/nice-select2.js"
https://github.com/bluzky/nice-select2/blob/master/src/js/nice-select2.js

**Comment by GitRon** [comment]
I get issues installing it with `import` as well... have to add the JS file manually to make webpack work.

**Comment by Tsjippy** [comment]
fixed

**Comment by GitRon** [comment]
Awesome! ❤️ Do you know when the fix will be released?
